version: '3.1'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      # - ./src/library_service/sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./postgres/:/docker-entrypoint-initdb.d/
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 25s
      timeout: 15s
      retries: 10

  library_service:
    image: library_service
    container_name: library_service
    build:
      context: "."
      dockerfile: ./docker/library.Dockerfile
    ports:
      - "8060:8060"
    networks:
      - default
    depends_on:
      postgres_db:
        condition: service_healthy

  rating_service:
    image: rating_service
    container_name: rating_service
    build:
      context: "."
      dockerfile: ./docker/rating.Dockerfile
    ports:
      - "8050:8050"
    networks:
      - default
    depends_on:
      postgres_db:
        condition: service_healthy

  reservation_service:
    image: reservation_service
    container_name: reservation_service
    build:
      context: "."
      dockerfile: ./docker/reservation.Dockerfile
    ports:
      - "8070:8070"
    networks:
      - default
    depends_on:
      postgres_db:
        condition: service_healthy

  gateway_service:
    image: gateway_service
    container_name: gateway_service
    build:
      context: "."
      dockerfile: ./docker/gateway.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default


volumes:
  pg_data:
    driver: local
  # pg_data_bonus:
  #   driver: local
  # pg_data_flight:
  #   driver: local

networks:
  default:
